version: '3.4'

services:
  orderservice.api:
    image: otdemo/orderserviceapi
    build:
      context: .
      dockerfile: src/OrderService/OrderService.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - Endpoints__StockService=http://stockservice.api
      - Tracing__Endpoint=jaeger
    ports:
      - "31001:80"
    restart: always

  stockservice.api:
    image: otdemo/stockserviceapi
    build:
      context: .
      dockerfile: src/StockService/StockService.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - Tracing__Endpoint=jaeger
    ports:
      - "31002:80"
    restart: always

  jaeger:
    image: jaegertracing/all-in-one:1.13
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
